# Generated by Django 5.2 on 2025-04-28 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='zip_code',
            new_name='zipcode',
        ),
    ]
