# Generated by Django 5.1.5 on 2025-05-24 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_slider_remove_brand_slug_remove_size_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('tags', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(default='products/default.jpg', null=True, upload_to='products/')),
                ('ex_image1', models.ImageField(default='default.jpg', null=True, upload_to='products/')),
                ('ex_image2', models.ImageField(default='default.jpg', null=True, upload_to='products/')),
                ('ex_image3', models.ImageField(default='default.jpg', null=True, upload_to='products/')),
                ('size', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('condition', models.CharField(choices=[('new', 'New'), ('sale', 'sale')], max_length=100)),
                ('new_arrival', models.BooleanField(default=False)),
                ('top_rated', models.BooleanField(default=False)),
                ('best_selling', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('featured', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.catagory')),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
