# Generated by Django 5.1.5 on 2025-05-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_alter_review_product_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ex_image1',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ex_image2',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ex_image3',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
